name: freezed_mappable

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: any
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.2.0
  dart_mappable_builder: any
  freezed: ^3.0.0-0.0.dev
  lints: ^5.1.1
